client CSR1kv-Router01 {
    ipaddr = 192.168.1.194
    secret = Pa$$w0rd123!
    shortname = csr
    require_message_authenticator = no
    limit_proxy_state = true
}

client CSR1kv-Router01 {
    ipaddr = 192.168.1.194
    secret = Pa$$w0rd123!
    shortname = csr
    require_message_authenticator = no
    limit_proxy_state = true
}

client CiscoNexus9000 {
    ipaddr = 192.168.1.193
    secret = Pa$$w0rd123!
    shortname = nxs
    require_message_authenticator = no
    limit_proxy_state = true
}

client csr-router1 {
    ipaddr = 192.168.1.8
    secret = Pa$$w0rd123!
    shortname = csr
    require_message_authenticator = no
    limit_proxy_state = true
}

client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    nastype = other
    require_message_authenticator = true
    limit_proxy_state = yes
}