// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: telemetry/telemetry_bis.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Telemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to NodeId:
	//
	//	*Telemetry_NodeIdStr
	NodeId isTelemetry_NodeId `protobuf_oneof:"node_id"`
	// Types that are valid to be assigned to Subscription:
	//
	//	*Telemetry_SubscriptionIdStr
	Subscription        isTelemetry_Subscription `protobuf_oneof:"subscription"`
	EncodingPath        string                   `protobuf:"bytes,6,opt,name=encoding_path,json=encodingPath,proto3" json:"encoding_path,omitempty"`
	CollectionId        uint64                   `protobuf:"varint,8,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	CollectionStartTime uint64                   `protobuf:"varint,9,opt,name=collection_start_time,json=collectionStartTime,proto3" json:"collection_start_time,omitempty"`
	MsgTimestamp        uint64                   `protobuf:"varint,10,opt,name=msg_timestamp,json=msgTimestamp,proto3" json:"msg_timestamp,omitempty"`
	DataGpbkv           []*TelemetryField        `protobuf:"bytes,11,rep,name=data_gpbkv,json=dataGpbkv,proto3" json:"data_gpbkv,omitempty"`
	DataGpb             *TelemetryGPBTable       `protobuf:"bytes,12,opt,name=data_gpb,json=dataGpb,proto3" json:"data_gpb,omitempty"`
	CollectionEndTime   uint64                   `protobuf:"varint,13,opt,name=collection_end_time,json=collectionEndTime,proto3" json:"collection_end_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_bis_proto_rawDescGZIP(), []int{0}
}

func (x *Telemetry) GetNodeId() isTelemetry_NodeId {
	if x != nil {
		return x.NodeId
	}
	return nil
}

func (x *Telemetry) GetNodeIdStr() string {
	if x != nil {
		if x, ok := x.NodeId.(*Telemetry_NodeIdStr); ok {
			return x.NodeIdStr
		}
	}
	return ""
}

func (x *Telemetry) GetSubscription() isTelemetry_Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Telemetry) GetSubscriptionIdStr() string {
	if x != nil {
		if x, ok := x.Subscription.(*Telemetry_SubscriptionIdStr); ok {
			return x.SubscriptionIdStr
		}
	}
	return ""
}

func (x *Telemetry) GetEncodingPath() string {
	if x != nil {
		return x.EncodingPath
	}
	return ""
}

func (x *Telemetry) GetCollectionId() uint64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *Telemetry) GetCollectionStartTime() uint64 {
	if x != nil {
		return x.CollectionStartTime
	}
	return 0
}

func (x *Telemetry) GetMsgTimestamp() uint64 {
	if x != nil {
		return x.MsgTimestamp
	}
	return 0
}

func (x *Telemetry) GetDataGpbkv() []*TelemetryField {
	if x != nil {
		return x.DataGpbkv
	}
	return nil
}

func (x *Telemetry) GetDataGpb() *TelemetryGPBTable {
	if x != nil {
		return x.DataGpb
	}
	return nil
}

func (x *Telemetry) GetCollectionEndTime() uint64 {
	if x != nil {
		return x.CollectionEndTime
	}
	return 0
}

type isTelemetry_NodeId interface {
	isTelemetry_NodeId()
}

type Telemetry_NodeIdStr struct {
	NodeIdStr string `protobuf:"bytes,1,opt,name=node_id_str,json=nodeIdStr,proto3,oneof"`
}

func (*Telemetry_NodeIdStr) isTelemetry_NodeId() {}

type isTelemetry_Subscription interface {
	isTelemetry_Subscription()
}

type Telemetry_SubscriptionIdStr struct {
	SubscriptionIdStr string `protobuf:"bytes,3,opt,name=subscription_id_str,json=subscriptionIdStr,proto3,oneof"`
}

func (*Telemetry_SubscriptionIdStr) isTelemetry_Subscription() {}

type TelemetryField struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ValueByType:
	//
	//	*TelemetryField_BytesValue
	//	*TelemetryField_StringValue
	//	*TelemetryField_BoolValue
	//	*TelemetryField_Uint32Value
	//	*TelemetryField_Uint64Value
	//	*TelemetryField_Sint32Value
	//	*TelemetryField_Sint64Value
	//	*TelemetryField_DoubleValue
	//	*TelemetryField_FloatValue
	ValueByType   isTelemetryField_ValueByType `protobuf_oneof:"value_by_type"`
	Fields        []*TelemetryField            `protobuf:"bytes,15,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryField) Reset() {
	*x = TelemetryField{}
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryField) ProtoMessage() {}

func (x *TelemetryField) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryField.ProtoReflect.Descriptor instead.
func (*TelemetryField) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_bis_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryField) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryField) GetValueByType() isTelemetryField_ValueByType {
	if x != nil {
		return x.ValueByType
	}
	return nil
}

func (x *TelemetryField) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *TelemetryField) GetStringValue() string {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TelemetryField) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TelemetryField) GetUint32Value() uint32 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_Uint32Value); ok {
			return x.Uint32Value
		}
	}
	return 0
}

func (x *TelemetryField) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

func (x *TelemetryField) GetSint32Value() int32 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_Sint32Value); ok {
			return x.Sint32Value
		}
	}
	return 0
}

func (x *TelemetryField) GetSint64Value() int64 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_Sint64Value); ok {
			return x.Sint64Value
		}
	}
	return 0
}

func (x *TelemetryField) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TelemetryField) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.ValueByType.(*TelemetryField_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *TelemetryField) GetFields() []*TelemetryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type isTelemetryField_ValueByType interface {
	isTelemetryField_ValueByType()
}

type TelemetryField_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type TelemetryField_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type TelemetryField_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TelemetryField_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,7,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type TelemetryField_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,8,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type TelemetryField_Sint32Value struct {
	Sint32Value int32 `protobuf:"zigzag32,9,opt,name=sint32_value,json=sint32Value,proto3,oneof"`
}

type TelemetryField_Sint64Value struct {
	Sint64Value int64 `protobuf:"zigzag64,10,opt,name=sint64_value,json=sint64Value,proto3,oneof"`
}

type TelemetryField_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,11,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type TelemetryField_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,12,opt,name=float_value,json=floatValue,proto3,oneof"`
}

func (*TelemetryField_BytesValue) isTelemetryField_ValueByType() {}

func (*TelemetryField_StringValue) isTelemetryField_ValueByType() {}

func (*TelemetryField_BoolValue) isTelemetryField_ValueByType() {}

func (*TelemetryField_Uint32Value) isTelemetryField_ValueByType() {}

func (*TelemetryField_Uint64Value) isTelemetryField_ValueByType() {}

func (*TelemetryField_Sint32Value) isTelemetryField_ValueByType() {}

func (*TelemetryField_Sint64Value) isTelemetryField_ValueByType() {}

func (*TelemetryField_DoubleValue) isTelemetryField_ValueByType() {}

func (*TelemetryField_FloatValue) isTelemetryField_ValueByType() {}

type TelemetryGPBTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []*TelemetryRowGPB     `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryGPBTable) Reset() {
	*x = TelemetryGPBTable{}
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryGPBTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryGPBTable) ProtoMessage() {}

func (x *TelemetryGPBTable) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryGPBTable.ProtoReflect.Descriptor instead.
func (*TelemetryGPBTable) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_bis_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryGPBTable) GetRow() []*TelemetryRowGPB {
	if x != nil {
		return x.Row
	}
	return nil
}

type TelemetryRowGPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Keys          []byte                 `protobuf:"bytes,10,opt,name=keys,proto3" json:"keys,omitempty"`
	Content       []byte                 `protobuf:"bytes,11,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRowGPB) Reset() {
	*x = TelemetryRowGPB{}
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRowGPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRowGPB) ProtoMessage() {}

func (x *TelemetryRowGPB) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_bis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRowGPB.ProtoReflect.Descriptor instead.
func (*TelemetryRowGPB) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_bis_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryRowGPB) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryRowGPB) GetKeys() []byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *TelemetryRowGPB) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_telemetry_telemetry_bis_proto protoreflect.FileDescriptor

const file_telemetry_telemetry_bis_proto_rawDesc = "" +
	"\n" +
	"\x1dtelemetry/telemetry_bis.proto\x12\ttelemetry\"\xc0\x03\n" +
	"\tTelemetry\x12 \n" +
	"\vnode_id_str\x18\x01 \x01(\tH\x00R\tnodeIdStr\x120\n" +
	"\x13subscription_id_str\x18\x03 \x01(\tH\x01R\x11subscriptionIdStr\x12#\n" +
	"\rencoding_path\x18\x06 \x01(\tR\fencodingPath\x12#\n" +
	"\rcollection_id\x18\b \x01(\x04R\fcollectionId\x122\n" +
	"\x15collection_start_time\x18\t \x01(\x04R\x13collectionStartTime\x12#\n" +
	"\rmsg_timestamp\x18\n" +
	" \x01(\x04R\fmsgTimestamp\x128\n" +
	"\n" +
	"data_gpbkv\x18\v \x03(\v2\x19.telemetry.TelemetryFieldR\tdataGpbkv\x127\n" +
	"\bdata_gpb\x18\f \x01(\v2\x1c.telemetry.TelemetryGPBTableR\adataGpb\x12.\n" +
	"\x13collection_end_time\x18\r \x01(\x04R\x11collectionEndTimeB\t\n" +
	"\anode_idB\x0e\n" +
	"\fsubscription\"\xcb\x03\n" +
	"\x0eTelemetryField\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fuint32_value\x18\a \x01(\rH\x00R\vuint32Value\x12#\n" +
	"\fuint64_value\x18\b \x01(\x04H\x00R\vuint64Value\x12#\n" +
	"\fsint32_value\x18\t \x01(\x11H\x00R\vsint32Value\x12#\n" +
	"\fsint64_value\x18\n" +
	" \x01(\x12H\x00R\vsint64Value\x12#\n" +
	"\fdouble_value\x18\v \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vfloat_value\x18\f \x01(\x02H\x00R\n" +
	"floatValue\x121\n" +
	"\x06fields\x18\x0f \x03(\v2\x19.telemetry.TelemetryFieldR\x06fieldsB\x0f\n" +
	"\rvalue_by_type\"A\n" +
	"\x11TelemetryGPBTable\x12,\n" +
	"\x03row\x18\x01 \x03(\v2\x1a.telemetry.TelemetryRowGPBR\x03row\"]\n" +
	"\x0fTelemetryRowGPB\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x12\n" +
	"\x04keys\x18\n" +
	" \x01(\fR\x04keys\x12\x18\n" +
	"\acontent\x18\v \x01(\fR\acontentB\x1bZ\x19nexus-telemetry/telemetryb\x06proto3"

var (
	file_telemetry_telemetry_bis_proto_rawDescOnce sync.Once
	file_telemetry_telemetry_bis_proto_rawDescData []byte
)

func file_telemetry_telemetry_bis_proto_rawDescGZIP() []byte {
	file_telemetry_telemetry_bis_proto_rawDescOnce.Do(func() {
		file_telemetry_telemetry_bis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_bis_proto_rawDesc), len(file_telemetry_telemetry_bis_proto_rawDesc)))
	})
	return file_telemetry_telemetry_bis_proto_rawDescData
}

var file_telemetry_telemetry_bis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_telemetry_telemetry_bis_proto_goTypes = []any{
	(*Telemetry)(nil),         // 0: telemetry.Telemetry
	(*TelemetryField)(nil),    // 1: telemetry.TelemetryField
	(*TelemetryGPBTable)(nil), // 2: telemetry.TelemetryGPBTable
	(*TelemetryRowGPB)(nil),   // 3: telemetry.TelemetryRowGPB
}
var file_telemetry_telemetry_bis_proto_depIdxs = []int32{
	1, // 0: telemetry.Telemetry.data_gpbkv:type_name -> telemetry.TelemetryField
	2, // 1: telemetry.Telemetry.data_gpb:type_name -> telemetry.TelemetryGPBTable
	1, // 2: telemetry.TelemetryField.fields:type_name -> telemetry.TelemetryField
	3, // 3: telemetry.TelemetryGPBTable.row:type_name -> telemetry.TelemetryRowGPB
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_telemetry_telemetry_bis_proto_init() }
func file_telemetry_telemetry_bis_proto_init() {
	if File_telemetry_telemetry_bis_proto != nil {
		return
	}
	file_telemetry_telemetry_bis_proto_msgTypes[0].OneofWrappers = []any{
		(*Telemetry_NodeIdStr)(nil),
		(*Telemetry_SubscriptionIdStr)(nil),
	}
	file_telemetry_telemetry_bis_proto_msgTypes[1].OneofWrappers = []any{
		(*TelemetryField_BytesValue)(nil),
		(*TelemetryField_StringValue)(nil),
		(*TelemetryField_BoolValue)(nil),
		(*TelemetryField_Uint32Value)(nil),
		(*TelemetryField_Uint64Value)(nil),
		(*TelemetryField_Sint32Value)(nil),
		(*TelemetryField_Sint64Value)(nil),
		(*TelemetryField_DoubleValue)(nil),
		(*TelemetryField_FloatValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_bis_proto_rawDesc), len(file_telemetry_telemetry_bis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_telemetry_bis_proto_goTypes,
		DependencyIndexes: file_telemetry_telemetry_bis_proto_depIdxs,
		MessageInfos:      file_telemetry_telemetry_bis_proto_msgTypes,
	}.Build()
	File_telemetry_telemetry_bis_proto = out.File
	file_telemetry_telemetry_bis_proto_goTypes = nil
	file_telemetry_telemetry_bis_proto_depIdxs = nil
}
