FROM python:3.11-slim

WORKDIR /app/traps

# Copy app files
COPY consumer.py .

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "consumer.py"]