FROM python:3.11

WORKDIR /app/backend

COPY requirements.txt .

# Install Python dependencies
RUN pip install -r requirements.txt
RUN pip install alembic ansible paramiko ansible-pylibssh

# Install system packages for Ansible and libssh
RUN apt-get update && \
    apt-get install -y netcat-traditional ansible sshpass libssh-4 --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY . .
COPY entrypoint.sh .

# Set entrypoint
ENTRYPOINT ["./entrypoint.sh"]