FROM python:3.11-slim

WORKDIR /app/syslogs

# Copy app files
COPY consumer.py .
COPY utils.py .

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-u", "consumer.py"]