// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cisco_grpc_dialout.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_cisco_5fgrpc_5fdialout_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_cisco_5fgrpc_5fdialout_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cisco_5fgrpc_5fdialout_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cisco_5fgrpc_5fdialout_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_cisco_5fgrpc_5fdialout_2eproto;
namespace cisco_grpc_dialout {
class DialoutArgs;
struct DialoutArgsDefaultTypeInternal;
extern DialoutArgsDefaultTypeInternal _DialoutArgs_default_instance_;
class DialoutMsg;
struct DialoutMsgDefaultTypeInternal;
extern DialoutMsgDefaultTypeInternal _DialoutMsg_default_instance_;
}  // namespace cisco_grpc_dialout
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cisco_grpc_dialout {

// ===================================================================


// -------------------------------------------------------------------

class DialoutMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cisco_grpc_dialout.DialoutMsg) */ {
 public:
  inline DialoutMsg() : DialoutMsg(nullptr) {}
  ~DialoutMsg() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DialoutMsg(
      ::google::protobuf::internal::ConstantInitialized);

  inline DialoutMsg(const DialoutMsg& from) : DialoutMsg(nullptr, from) {}
  inline DialoutMsg(DialoutMsg&& from) noexcept
      : DialoutMsg(nullptr, std::move(from)) {}
  inline DialoutMsg& operator=(const DialoutMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline DialoutMsg& operator=(DialoutMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DialoutMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const DialoutMsg* internal_default_instance() {
    return reinterpret_cast<const DialoutMsg*>(
        &_DialoutMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DialoutMsg& a, DialoutMsg& b) { a.Swap(&b); }
  inline void Swap(DialoutMsg* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DialoutMsg* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DialoutMsg* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<DialoutMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DialoutMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DialoutMsg& from) { DialoutMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DialoutMsg* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cisco_grpc_dialout.DialoutMsg"; }

 protected:
  explicit DialoutMsg(::google::protobuf::Arena* arena);
  DialoutMsg(::google::protobuf::Arena* arena, const DialoutMsg& from);
  DialoutMsg(::google::protobuf::Arena* arena, DialoutMsg&& from) noexcept
      : DialoutMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReqIdFieldNumber = 1,
    kDataFieldNumber = 2,
    kErrorsFieldNumber = 3,
  };
  // string ReqId = 1;
  void clear_reqid() ;
  const std::string& reqid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_reqid(Arg_&& arg, Args_... args);
  std::string* mutable_reqid();
  PROTOBUF_NODISCARD std::string* release_reqid();
  void set_allocated_reqid(std::string* value);

  private:
  const std::string& _internal_reqid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reqid(
      const std::string& value);
  std::string* _internal_mutable_reqid();

  public:
  // bytes data = 2;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // string errors = 3;
  void clear_errors() ;
  const std::string& errors() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_errors(Arg_&& arg, Args_... args);
  std::string* mutable_errors();
  PROTOBUF_NODISCARD std::string* release_errors();
  void set_allocated_errors(std::string* value);

  private:
  const std::string& _internal_errors() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errors(
      const std::string& value);
  std::string* _internal_mutable_errors();

  public:
  // @@protoc_insertion_point(class_scope:cisco_grpc_dialout.DialoutMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      49, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_DialoutMsg_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DialoutMsg& from_msg);
    ::google::protobuf::internal::ArenaStringPtr reqid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr errors_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cisco_5fgrpc_5fdialout_2eproto;
};
// -------------------------------------------------------------------

class DialoutArgs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cisco_grpc_dialout.DialoutArgs) */ {
 public:
  inline DialoutArgs() : DialoutArgs(nullptr) {}
  ~DialoutArgs() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DialoutArgs(
      ::google::protobuf::internal::ConstantInitialized);

  inline DialoutArgs(const DialoutArgs& from) : DialoutArgs(nullptr, from) {}
  inline DialoutArgs(DialoutArgs&& from) noexcept
      : DialoutArgs(nullptr, std::move(from)) {}
  inline DialoutArgs& operator=(const DialoutArgs& from) {
    CopyFrom(from);
    return *this;
  }
  inline DialoutArgs& operator=(DialoutArgs&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DialoutArgs& default_instance() {
    return *internal_default_instance();
  }
  static inline const DialoutArgs* internal_default_instance() {
    return reinterpret_cast<const DialoutArgs*>(
        &_DialoutArgs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(DialoutArgs& a, DialoutArgs& b) { a.Swap(&b); }
  inline void Swap(DialoutArgs* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DialoutArgs* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DialoutArgs* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<DialoutArgs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DialoutArgs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DialoutArgs& from) { DialoutArgs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DialoutArgs* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "cisco_grpc_dialout.DialoutArgs"; }

 protected:
  explicit DialoutArgs(::google::protobuf::Arena* arena);
  DialoutArgs(::google::protobuf::Arena* arena, const DialoutArgs& from);
  DialoutArgs(::google::protobuf::Arena* arena, DialoutArgs&& from) noexcept
      : DialoutArgs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReqIdFieldNumber = 1,
    kErrorsFieldNumber = 2,
  };
  // string ReqId = 1;
  void clear_reqid() ;
  const std::string& reqid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_reqid(Arg_&& arg, Args_... args);
  std::string* mutable_reqid();
  PROTOBUF_NODISCARD std::string* release_reqid();
  void set_allocated_reqid(std::string* value);

  private:
  const std::string& _internal_reqid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reqid(
      const std::string& value);
  std::string* _internal_mutable_reqid();

  public:
  // string errors = 2;
  void clear_errors() ;
  const std::string& errors() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_errors(Arg_&& arg, Args_... args);
  std::string* mutable_errors();
  PROTOBUF_NODISCARD std::string* release_errors();
  void set_allocated_errors(std::string* value);

  private:
  const std::string& _internal_errors() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errors(
      const std::string& value);
  std::string* _internal_mutable_errors();

  public:
  // @@protoc_insertion_point(class_scope:cisco_grpc_dialout.DialoutArgs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      50, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_DialoutArgs_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DialoutArgs& from_msg);
    ::google::protobuf::internal::ArenaStringPtr reqid_;
    ::google::protobuf::internal::ArenaStringPtr errors_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cisco_5fgrpc_5fdialout_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DialoutMsg

// string ReqId = 1;
inline void DialoutMsg::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.ClearToEmpty();
}
inline const std::string& DialoutMsg::reqid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cisco_grpc_dialout.DialoutMsg.ReqId)
  return _internal_reqid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DialoutMsg::set_reqid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cisco_grpc_dialout.DialoutMsg.ReqId)
}
inline std::string* DialoutMsg::mutable_reqid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_reqid();
  // @@protoc_insertion_point(field_mutable:cisco_grpc_dialout.DialoutMsg.ReqId)
  return _s;
}
inline const std::string& DialoutMsg::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_.Get();
}
inline void DialoutMsg::_internal_set_reqid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.Set(value, GetArena());
}
inline std::string* DialoutMsg::_internal_mutable_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.reqid_.Mutable( GetArena());
}
inline std::string* DialoutMsg::release_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cisco_grpc_dialout.DialoutMsg.ReqId)
  return _impl_.reqid_.Release();
}
inline void DialoutMsg::set_allocated_reqid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.reqid_.IsDefault()) {
          _impl_.reqid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cisco_grpc_dialout.DialoutMsg.ReqId)
}

// bytes data = 2;
inline void DialoutMsg::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& DialoutMsg::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cisco_grpc_dialout.DialoutMsg.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DialoutMsg::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cisco_grpc_dialout.DialoutMsg.data)
}
inline std::string* DialoutMsg::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:cisco_grpc_dialout.DialoutMsg.data)
  return _s;
}
inline const std::string& DialoutMsg::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void DialoutMsg::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* DialoutMsg::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* DialoutMsg::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cisco_grpc_dialout.DialoutMsg.data)
  return _impl_.data_.Release();
}
inline void DialoutMsg::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cisco_grpc_dialout.DialoutMsg.data)
}

// string errors = 3;
inline void DialoutMsg::clear_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.ClearToEmpty();
}
inline const std::string& DialoutMsg::errors() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cisco_grpc_dialout.DialoutMsg.errors)
  return _internal_errors();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DialoutMsg::set_errors(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cisco_grpc_dialout.DialoutMsg.errors)
}
inline std::string* DialoutMsg::mutable_errors() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_errors();
  // @@protoc_insertion_point(field_mutable:cisco_grpc_dialout.DialoutMsg.errors)
  return _s;
}
inline const std::string& DialoutMsg::_internal_errors() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errors_.Get();
}
inline void DialoutMsg::_internal_set_errors(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.Set(value, GetArena());
}
inline std::string* DialoutMsg::_internal_mutable_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.errors_.Mutable( GetArena());
}
inline std::string* DialoutMsg::release_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cisco_grpc_dialout.DialoutMsg.errors)
  return _impl_.errors_.Release();
}
inline void DialoutMsg::set_allocated_errors(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.errors_.IsDefault()) {
          _impl_.errors_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cisco_grpc_dialout.DialoutMsg.errors)
}

// -------------------------------------------------------------------

// DialoutArgs

// string ReqId = 1;
inline void DialoutArgs::clear_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.ClearToEmpty();
}
inline const std::string& DialoutArgs::reqid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cisco_grpc_dialout.DialoutArgs.ReqId)
  return _internal_reqid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DialoutArgs::set_reqid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cisco_grpc_dialout.DialoutArgs.ReqId)
}
inline std::string* DialoutArgs::mutable_reqid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_reqid();
  // @@protoc_insertion_point(field_mutable:cisco_grpc_dialout.DialoutArgs.ReqId)
  return _s;
}
inline const std::string& DialoutArgs::_internal_reqid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reqid_.Get();
}
inline void DialoutArgs::_internal_set_reqid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.Set(value, GetArena());
}
inline std::string* DialoutArgs::_internal_mutable_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.reqid_.Mutable( GetArena());
}
inline std::string* DialoutArgs::release_reqid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cisco_grpc_dialout.DialoutArgs.ReqId)
  return _impl_.reqid_.Release();
}
inline void DialoutArgs::set_allocated_reqid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reqid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.reqid_.IsDefault()) {
          _impl_.reqid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cisco_grpc_dialout.DialoutArgs.ReqId)
}

// string errors = 2;
inline void DialoutArgs::clear_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.ClearToEmpty();
}
inline const std::string& DialoutArgs::errors() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cisco_grpc_dialout.DialoutArgs.errors)
  return _internal_errors();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DialoutArgs::set_errors(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:cisco_grpc_dialout.DialoutArgs.errors)
}
inline std::string* DialoutArgs::mutable_errors() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_errors();
  // @@protoc_insertion_point(field_mutable:cisco_grpc_dialout.DialoutArgs.errors)
  return _s;
}
inline const std::string& DialoutArgs::_internal_errors() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.errors_.Get();
}
inline void DialoutArgs::_internal_set_errors(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.Set(value, GetArena());
}
inline std::string* DialoutArgs::_internal_mutable_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.errors_.Mutable( GetArena());
}
inline std::string* DialoutArgs::release_errors() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cisco_grpc_dialout.DialoutArgs.errors)
  return _impl_.errors_.Release();
}
inline void DialoutArgs::set_allocated_errors(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.errors_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.errors_.IsDefault()) {
          _impl_.errors_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:cisco_grpc_dialout.DialoutArgs.errors)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cisco_grpc_dialout


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_cisco_5fgrpc_5fdialout_2eproto_2epb_2eh
