// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cisco_grpc_dialout.proto
// Protobuf C++ Version: 5.28.2

#include "cisco_grpc_dialout.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cisco_grpc_dialout {

inline constexpr DialoutMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : reqid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        errors_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DialoutMsg::DialoutMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DialoutMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DialoutMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DialoutMsgDefaultTypeInternal() {}
  union {
    DialoutMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DialoutMsgDefaultTypeInternal _DialoutMsg_default_instance_;

inline constexpr DialoutArgs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : reqid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        errors_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DialoutArgs::DialoutArgs(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DialoutArgsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DialoutArgsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DialoutArgsDefaultTypeInternal() {}
  union {
    DialoutArgs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DialoutArgsDefaultTypeInternal _DialoutArgs_default_instance_;
}  // namespace cisco_grpc_dialout
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cisco_5fgrpc_5fdialout_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cisco_5fgrpc_5fdialout_2eproto = nullptr;
const ::uint32_t
    TableStruct_cisco_5fgrpc_5fdialout_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutMsg, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutMsg, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutMsg, _impl_.errors_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutArgs, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutArgs, _impl_.reqid_),
        PROTOBUF_FIELD_OFFSET(::cisco_grpc_dialout::DialoutArgs, _impl_.errors_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::cisco_grpc_dialout::DialoutMsg)},
        {11, -1, -1, sizeof(::cisco_grpc_dialout::DialoutArgs)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::cisco_grpc_dialout::_DialoutMsg_default_instance_._instance,
    &::cisco_grpc_dialout::_DialoutArgs_default_instance_._instance,
};
const char descriptor_table_protodef_cisco_5fgrpc_5fdialout_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030cisco_grpc_dialout.proto\022\022cisco_grpc_d"
    "ialout\"9\n\nDialoutMsg\022\r\n\005ReqId\030\001 \001(\t\022\014\n\004d"
    "ata\030\002 \001(\014\022\016\n\006errors\030\003 \001(\t\",\n\013DialoutArgs"
    "\022\r\n\005ReqId\030\001 \001(\t\022\016\n\006errors\030\002 \001(\t2]\n\013GRPCD"
    "ialout\022N\n\007Dialout\022\036.cisco_grpc_dialout.D"
    "ialoutMsg\032\037.cisco_grpc_dialout.DialoutAr"
    "gs\"\000(\001b\006proto3"
};
static ::absl::once_flag descriptor_table_cisco_5fgrpc_5fdialout_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cisco_5fgrpc_5fdialout_2eproto = {
    false,
    false,
    254,
    descriptor_table_protodef_cisco_5fgrpc_5fdialout_2eproto,
    "cisco_grpc_dialout.proto",
    &descriptor_table_cisco_5fgrpc_5fdialout_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_cisco_5fgrpc_5fdialout_2eproto::offsets,
    file_level_enum_descriptors_cisco_5fgrpc_5fdialout_2eproto,
    file_level_service_descriptors_cisco_5fgrpc_5fdialout_2eproto,
};
namespace cisco_grpc_dialout {
// ===================================================================

class DialoutMsg::_Internal {
 public:
};

DialoutMsg::DialoutMsg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cisco_grpc_dialout.DialoutMsg)
}
inline PROTOBUF_NDEBUG_INLINE DialoutMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cisco_grpc_dialout::DialoutMsg& from_msg)
      : reqid_(arena, from.reqid_),
        data_(arena, from.data_),
        errors_(arena, from.errors_),
        _cached_size_{0} {}

DialoutMsg::DialoutMsg(
    ::google::protobuf::Arena* arena,
    const DialoutMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DialoutMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cisco_grpc_dialout.DialoutMsg)
}
inline PROTOBUF_NDEBUG_INLINE DialoutMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : reqid_(arena),
        data_(arena),
        errors_(arena),
        _cached_size_{0} {}

inline void DialoutMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DialoutMsg::~DialoutMsg() {
  // @@protoc_insertion_point(destructor:cisco_grpc_dialout.DialoutMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DialoutMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.reqid_.Destroy();
  _impl_.data_.Destroy();
  _impl_.errors_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    DialoutMsg::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_DialoutMsg_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &DialoutMsg::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<DialoutMsg>(),
            ::google::protobuf::Message::GetNewImpl<DialoutMsg>(),
            ::google::protobuf::Message::GetClearImpl<DialoutMsg>(), &DialoutMsg::ByteSizeLong,
                &DialoutMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_._cached_size_),
            false,
        },
        &DialoutMsg::kDescriptorMethods,
        &descriptor_table_cisco_5fgrpc_5fdialout_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* DialoutMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 49, 2> DialoutMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cisco_grpc_dialout::DialoutMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string ReqId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.reqid_)}},
    // bytes data = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.data_)}},
    // string errors = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.errors_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ReqId = 1;
    {PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.reqid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 2;
    {PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string errors = 3;
    {PROTOBUF_FIELD_OFFSET(DialoutMsg, _impl_.errors_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\5\0\6\0\0\0\0"
    "cisco_grpc_dialout.DialoutMsg"
    "ReqId"
    "errors"
  }},
};

PROTOBUF_NOINLINE void DialoutMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:cisco_grpc_dialout.DialoutMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqid_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _impl_.errors_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DialoutMsg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DialoutMsg& this_ = static_cast<const DialoutMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DialoutMsg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DialoutMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:cisco_grpc_dialout.DialoutMsg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string ReqId = 1;
          if (!this_._internal_reqid().empty()) {
            const std::string& _s = this_._internal_reqid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cisco_grpc_dialout.DialoutMsg.ReqId");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bytes data = 2;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // string errors = 3;
          if (!this_._internal_errors().empty()) {
            const std::string& _s = this_._internal_errors();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cisco_grpc_dialout.DialoutMsg.errors");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:cisco_grpc_dialout.DialoutMsg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DialoutMsg::ByteSizeLong(const MessageLite& base) {
          const DialoutMsg& this_ = static_cast<const DialoutMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DialoutMsg::ByteSizeLong() const {
          const DialoutMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:cisco_grpc_dialout.DialoutMsg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string ReqId = 1;
            if (!this_._internal_reqid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_reqid());
            }
            // bytes data = 2;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_data());
            }
            // string errors = 3;
            if (!this_._internal_errors().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_errors());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DialoutMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DialoutMsg*>(&to_msg);
  auto& from = static_cast<const DialoutMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cisco_grpc_dialout.DialoutMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reqid().empty()) {
    _this->_internal_set_reqid(from._internal_reqid());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (!from._internal_errors().empty()) {
    _this->_internal_set_errors(from._internal_errors());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DialoutMsg::CopyFrom(const DialoutMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cisco_grpc_dialout.DialoutMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DialoutMsg::InternalSwap(DialoutMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reqid_, &other->_impl_.reqid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.errors_, &other->_impl_.errors_, arena);
}

::google::protobuf::Metadata DialoutMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DialoutArgs::_Internal {
 public:
};

DialoutArgs::DialoutArgs(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cisco_grpc_dialout.DialoutArgs)
}
inline PROTOBUF_NDEBUG_INLINE DialoutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cisco_grpc_dialout::DialoutArgs& from_msg)
      : reqid_(arena, from.reqid_),
        errors_(arena, from.errors_),
        _cached_size_{0} {}

DialoutArgs::DialoutArgs(
    ::google::protobuf::Arena* arena,
    const DialoutArgs& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DialoutArgs* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cisco_grpc_dialout.DialoutArgs)
}
inline PROTOBUF_NDEBUG_INLINE DialoutArgs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : reqid_(arena),
        errors_(arena),
        _cached_size_{0} {}

inline void DialoutArgs::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DialoutArgs::~DialoutArgs() {
  // @@protoc_insertion_point(destructor:cisco_grpc_dialout.DialoutArgs)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DialoutArgs::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.reqid_.Destroy();
  _impl_.errors_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    DialoutArgs::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_DialoutArgs_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &DialoutArgs::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<DialoutArgs>(),
            ::google::protobuf::Message::GetNewImpl<DialoutArgs>(),
            ::google::protobuf::Message::GetClearImpl<DialoutArgs>(), &DialoutArgs::ByteSizeLong,
                &DialoutArgs::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(DialoutArgs, _impl_._cached_size_),
            false,
        },
        &DialoutArgs::kDescriptorMethods,
        &descriptor_table_cisco_5fgrpc_5fdialout_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* DialoutArgs::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2> DialoutArgs::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cisco_grpc_dialout::DialoutArgs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string errors = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DialoutArgs, _impl_.errors_)}},
    // string ReqId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(DialoutArgs, _impl_.reqid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ReqId = 1;
    {PROTOBUF_FIELD_OFFSET(DialoutArgs, _impl_.reqid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string errors = 2;
    {PROTOBUF_FIELD_OFFSET(DialoutArgs, _impl_.errors_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\5\6\0\0\0\0\0"
    "cisco_grpc_dialout.DialoutArgs"
    "ReqId"
    "errors"
  }},
};

PROTOBUF_NOINLINE void DialoutArgs::Clear() {
// @@protoc_insertion_point(message_clear_start:cisco_grpc_dialout.DialoutArgs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqid_.ClearToEmpty();
  _impl_.errors_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DialoutArgs::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DialoutArgs& this_ = static_cast<const DialoutArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DialoutArgs::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DialoutArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:cisco_grpc_dialout.DialoutArgs)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string ReqId = 1;
          if (!this_._internal_reqid().empty()) {
            const std::string& _s = this_._internal_reqid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cisco_grpc_dialout.DialoutArgs.ReqId");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string errors = 2;
          if (!this_._internal_errors().empty()) {
            const std::string& _s = this_._internal_errors();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cisco_grpc_dialout.DialoutArgs.errors");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:cisco_grpc_dialout.DialoutArgs)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DialoutArgs::ByteSizeLong(const MessageLite& base) {
          const DialoutArgs& this_ = static_cast<const DialoutArgs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DialoutArgs::ByteSizeLong() const {
          const DialoutArgs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:cisco_grpc_dialout.DialoutArgs)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string ReqId = 1;
            if (!this_._internal_reqid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_reqid());
            }
            // string errors = 2;
            if (!this_._internal_errors().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_errors());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DialoutArgs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DialoutArgs*>(&to_msg);
  auto& from = static_cast<const DialoutArgs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cisco_grpc_dialout.DialoutArgs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reqid().empty()) {
    _this->_internal_set_reqid(from._internal_reqid());
  }
  if (!from._internal_errors().empty()) {
    _this->_internal_set_errors(from._internal_errors());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DialoutArgs::CopyFrom(const DialoutArgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cisco_grpc_dialout.DialoutArgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DialoutArgs::InternalSwap(DialoutArgs* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reqid_, &other->_impl_.reqid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.errors_, &other->_impl_.errors_, arena);
}

::google::protobuf::Metadata DialoutArgs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cisco_grpc_dialout
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_cisco_5fgrpc_5fdialout_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
