FROM golang:1.25-alpine AS builder

WORKDIR /app/telemetry/cisco/ios-xe/interface-oper-status

COPY telemetry/cisco/ios-xe/interface-oper-status/go.mod telemetry/cisco/ios-xe/interface-oper-status/go.sum ./

COPY telemetry/cisco/ios-xe/protobuf /app/telemetry/cisco/ios-xe/protobuf

COPY telemetry/cisco/ios-xe/interface-oper-status/. .

RUN go mod download

RUN go get github.com/redis/go-redis/v9

# Build your binary
RUN go build -o consumer . 

FROM alpine:3.18

WORKDIR /app/telemetry/cisco/ios-xe/interface-oper-status

COPY --from=builder /app/telemetry/cisco/ios-xe/interface-oper-status/consumer .

RUN apk add --no-cache bash

CMD ["./consumer"]
