FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY topology/consumer/go.mod topology/consumer/go.sum ./

RUN go mod download

COPY topology/consumer .

RUN go build -o topology-consumer ./main.go


FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/topology-consumer .

CMD ["./topology-consumer"]