FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY topology/producer/go.mod topology/producer/go.sum ./

RUN go mod download

COPY topology/producer .

RUN go build -o bgpls-producer ./main.go

FROM alpine:3.22

WORKDIR /app

COPY --from=builder /app/bgpls-producer .

CMD ["./bgpls-producer"]