FROM golang:1.25 AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends librdkafka-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY icmp-pinger/consumer/go.mod icmp-pinger/consumer/go.sum ./

RUN go mod download

COPY icmp-pinger/consumer/ .

RUN go build -o consumer .

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        librdkafka1 \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root

COPY --from=builder /app/consumer .

CMD ["./consumer"]