FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    librdkafka-dev \
    libjansson-dev \
    libpq-dev \
    uuid-dev \
    libcurl4-openssl-dev \
    libhiredis-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY traps/signals/ /app/traps/signals/

WORKDIR /app/traps/signals/

RUN cmake . && make

CMD ["./trap_signals"]
