FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    librdkafka-dev \
    libjansson-dev \
    libpq-dev \
    libcurl4-openssl-dev \
    uuid-dev \
    libhiredis-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set root working directory
WORKDIR /app

# Copy source to /app/syslogs/signals/
COPY /signals syslogs/signals/

# Move into the source directory
WORKDIR /app/syslogs/signals

# Build in-place
RUN cmake . && make

# Run the built binary
CMD ["./syslog_signals"]
