# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app/telemetry/cisco/ios-xe/producer

# Copy go.mod and go.sum first (for caching)
COPY telemetry/cisco/ios-xe/producer/go.mod telemetry/cisco/ios-xe/producer/go.sum ./

# Copy all source code
COPY telemetry/cisco/ios-xe/producer /app/telemetry/cisco/ios-xe/producer
COPY telemetry/cisco/ios-xe/protobuf /app/telemetry/cisco/ios-xe/protobuf

RUN go mod download

# Build the binary
RUN go build -o producer main.go

# Final stage: small image
FROM alpine:latest

WORKDIR /app
    
# Copy binary from builder
COPY --from=builder /app/telemetry/cisco/ios-xe/producer/producer .

# Expose the port your gRPC server listens on
EXPOSE 1163

# Command to run
CMD ["./producer"]
