# Dockerfile.consumer

FROM debian:bookworm-slim

ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    cmake \
    tzdata \
    libpq-dev \
    build-essential \
    librdkafka-dev \
    libcurl4-openssl-dev \
    libjansson-dev \
    uuid-dev \
    curl \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY netflow/consumer/ /app/netflow/consumer/

WORKDIR /app/netflow/consumer/

RUN cmake . && make

CMD ["./netflow_consumer"]