FROM golang:1.25-alpine AS builder

WORKDIR /app/telemetry/interface-stats

COPY telemetry/interface-stats/go.mod telemetry/interface-stats/go.sum ./

COPY telemetry/protobuf /app/telemetry/protobuf

COPY telemetry/interface-stats/. .

RUN go mod download

RUN go get github.com/redis/go-redis/v9

# Build your binary
RUN go build -o consumer . 

FROM alpine:3.18

WORKDIR /app/telemetry/interface-stats

COPY --from=builder /app/telemetry/interface-stats/consumer .

RUN apk add --no-cache bash

CMD ["./consumer"]
