FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    librdkafka-dev \
    libjansson-dev \
    libpq-dev \
    libcurl4-openssl-dev \
    uuid-dev \
    libhiredis-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set root working directory
WORKDIR /app

# Copy the source code
COPY . ./syslogs/signals/

# Create build directory
RUN mkdir -p /app/syslogs/signals/build

# Change to build directory and compile
WORKDIR /app/syslogs/signals/build
RUN cmake .. && make

# Run the built binary
CMD ["./syslog_signals"]
