FROM debian:bullseye

# Install build tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libpq-dev \
    postgresql-server-dev-all \
    librdkafka-dev \
    libjansson-dev \
    libpthread-stubs0-dev \
    uuid-dev \
    pkg-config \
    libhiredis-dev \
    ca-certificates \
    libcurl4-openssl-dev \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy only the consumer directory
COPY telemetry/signals/ /app/telemetry/signals/

# Create build directory
WORKDIR /app/telemetry/signals/

# Run CMake from 'build' directory, pointing to parent (which has CMakeLists.txt)
RUN cmake . && make

# Set default command
CMD ["./telemetry_signals"]
