FROM debian:bullseye

# Install build tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libpq-dev \
    postgresql-server-dev-all \
    librdkafka-dev \
    libjansson-dev \
    libpthread-stubs0-dev \
    uuid-dev \
    pkg-config \
    ca-certificates \
    libcurl4-openssl-dev \
    libssl-dev \
    && apt-get clean

# Set working directory
WORKDIR /app

# Copy only the consumer directory
COPY . ./syslogs/consumer/

# Create build directory
WORKDIR /app/syslogs/consumer/

# Run CMake from 'build' directory, pointing to parent (which has CMakeLists.txt)
RUN cmake . && make

# Set default command
CMD ["./syslog_consumer"]
