FROM golang:1.23-alpine AS builder

WORKDIR /app/telemetry/bgp-stats

COPY telemetry/bgp-stats/go.mod telemetry/bgp-stats/go.sum ./

COPY telemetry/protobuf /app/telemetry/protobuf

COPY telemetry/bgp-stats/. .

RUN go mod download

RUN go get github.com/joho/godotenv

# Build your binary
RUN go build -o consumer main.go

FROM alpine:3.18

WORKDIR /app/telemetry/bgp-stats

COPY --from=builder /app/telemetry/bgp-stats/consumer .

RUN apk add --no-cache bash

CMD ["./consumer"]
