FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    librdkafka-dev \
    libjansson-dev \
    libpq-dev \
    libcurl4-openssl-dev \
    uuid-dev \
    libhiredis-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY syslogs/signals/ /app/syslogs/signals/

WORKDIR /app/syslogs/signals/

RUN cmake . && make

# Run the built binary
CMD ["./syslog_signals"]
