FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    librdkafka-dev \
    libjansson-dev \
    libpq-dev \
    uuid-dev \
    libcurl4-openssl-dev \
    libhiredis-dev \
    pkg-config \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . ./traps/signals/

RUN mkdir -p /app/traps/signals/build
WORKDIR /app/traps/signals/build

RUN cmake .. && make

CMD ["./trap_signals"]
