FROM golang:1.23-alpine AS builder

WORKDIR /app/telemetry/memory-stats

COPY telemetry/memory-stats/ .

RUN go mod download

# Build your binary
RUN go build -o consumer main.go

FROM alpine:3.18

WORKDIR /app/telemetry/memory-stats

COPY --from=builder /app/telemetry/memory-stats/consumer .

RUN apk add --no-cache bash

CMD ["./consumer"]
