---
- name: Configure NetFlow on Cisco IOS XE device
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_host: "{{ router_ip }}"
    netflow_interfaces: []
    netflow_export_destination: "192.168.1.191"
    netflow_export_source: "GigabitEthernet1"
    netflow_export_port: 1162

  tasks:
    - name: Configure NetFlow flow record
      ios_config:
        lines:
          - "flow record RECORDER"
          - " match ipv4 source address"
          - " match ipv4 destination address"
          - " match transport source-port"
          - " match transport destination-port"
          - " match ipv4 protocol"
          - " collect interface input"
          - " collect interface output"
          - " collect counter bytes"
          - " collect counter packets"
          - " collect timestamp sys-uptime first"
          - " collect timestamp sys-uptime last"

    - name: Configure NetFlow flow exporter
      ios_config:
        lines:
          - "flow exporter EXPORTER"
          - " destination {{ netflow_export_destination }}"
          - " source {{ netflow_export_source }}"
          - " transport udp {{ netflow_export_port }}"
          - " template data timeout 60"
          - " option interface-table timeout 300"

    - name: Configure NetFlow flow monitor
      ios_config:
        lines:
          - "flow monitor MONITOR"
          - " exporter EXPORTER"
          - " cache timeout active 60"
          - " record RECORDER"

    - name: Apply NetFlow monitor to interfaces
      ios_config:
        parents: "interface {{ item }}"
        lines:
          - "ip flow monitor MONITOR input"
          - "ip flow monitor MONITOR output"
      loop: "{{ netflow_interfaces }}"