---
- name: Configure syslog on Cisco IOS device
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_host: "{{ router_ip }}"

  tasks:
    - name: Configure syslog host
      ios_config:
        lines:
          - "logging host {{ syslog_host }} transport udp port {{ syslog_port }}"
          - "logging trap {{ syslog_severity }}"