// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: mdt_dialout.proto

// Package implements gRPC Model Driven Telemetry service

package mdt_dialout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MdtDialoutArgs is the content pushed to the server
type MdtDialoutArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId int64                  `protobuf:"varint,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	// data carries the payload content.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Errors        string `protobuf:"bytes,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MdtDialoutArgs) Reset() {
	*x = MdtDialoutArgs{}
	mi := &file_mdt_dialout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MdtDialoutArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MdtDialoutArgs) ProtoMessage() {}

func (x *MdtDialoutArgs) ProtoReflect() protoreflect.Message {
	mi := &file_mdt_dialout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MdtDialoutArgs.ProtoReflect.Descriptor instead.
func (*MdtDialoutArgs) Descriptor() ([]byte, []int) {
	return file_mdt_dialout_proto_rawDescGZIP(), []int{0}
}

func (x *MdtDialoutArgs) GetReqId() int64 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *MdtDialoutArgs) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MdtDialoutArgs) GetErrors() string {
	if x != nil {
		return x.Errors
	}
	return ""
}

var File_mdt_dialout_proto protoreflect.FileDescriptor

const file_mdt_dialout_proto_rawDesc = "" +
	"\n" +
	"\x11mdt_dialout.proto\x12\vmdt_dialout\"R\n" +
	"\x0eMdtDialoutArgs\x12\x14\n" +
	"\x05ReqId\x18\x01 \x01(\x03R\x05ReqId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\tR\x06errors2^\n" +
	"\x0egRPCMdtDialout\x12L\n" +
	"\n" +
	"MdtDialout\x12\x1b.mdt_dialout.MdtDialoutArgs\x1a\x1b.mdt_dialout.MdtDialoutArgs\"\x00(\x010\x01B\x10Z\x0e./;mdt_dialoutb\x06proto3"

var (
	file_mdt_dialout_proto_rawDescOnce sync.Once
	file_mdt_dialout_proto_rawDescData []byte
)

func file_mdt_dialout_proto_rawDescGZIP() []byte {
	file_mdt_dialout_proto_rawDescOnce.Do(func() {
		file_mdt_dialout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mdt_dialout_proto_rawDesc), len(file_mdt_dialout_proto_rawDesc)))
	})
	return file_mdt_dialout_proto_rawDescData
}

var file_mdt_dialout_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mdt_dialout_proto_goTypes = []any{
	(*MdtDialoutArgs)(nil), // 0: mdt_dialout.MdtDialoutArgs
}
var file_mdt_dialout_proto_depIdxs = []int32{
	0, // 0: mdt_dialout.gRPCMdtDialout.MdtDialout:input_type -> mdt_dialout.MdtDialoutArgs
	0, // 1: mdt_dialout.gRPCMdtDialout.MdtDialout:output_type -> mdt_dialout.MdtDialoutArgs
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mdt_dialout_proto_init() }
func file_mdt_dialout_proto_init() {
	if File_mdt_dialout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mdt_dialout_proto_rawDesc), len(file_mdt_dialout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mdt_dialout_proto_goTypes,
		DependencyIndexes: file_mdt_dialout_proto_depIdxs,
		MessageInfos:      file_mdt_dialout_proto_msgTypes,
	}.Build()
	File_mdt_dialout_proto = out.File
	file_mdt_dialout_proto_goTypes = nil
	file_mdt_dialout_proto_depIdxs = nil
}
