[global.config]
  as = 500
  router-id = "192.168.1.201"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.1.194"
    peer-as = 500

  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ls"
      enabled = true
