name: Pristine AIOPS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push syslog consumer image
        uses: docker/build-push-action@v5
        with:
          context: ./syslogs/consumer
          file: ./dockerfiles/Dockerfile.syslog-consumer
          push: true
          tags: ghcr.io/rberbatovci/syslog-consumer:latest

      - name: Build and push syslog signals image
        uses: docker/build-push-action@v5
        with:
          context: ./syslogs/signals
          file: ./dockerfiles/Dockerfile.syslog-signals
          push: true
          tags: ghcr.io/rberbatovci/syslog-signals:latest
