name: Pristine AIOPS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #- name: Build and push backend image
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: ./backend
      #    file: ./backend/Dockerfile.backend
      #    push: true
      #    tags: ghcr.io/rberbatovci/backend:latest

      #- name: Build and push syslog producer image
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: ./syslogs
      #    file: ./dockerfiles/Dockerfile.syslog-producer
      #    push: true
      #    tags: ghcr.io/rberbatovci/syslog-producer:latest

      - name: Build and push syslog consumer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.syslog-consumer
          push: true
          tags: ghcr.io/rberbatovci/syslog-consumer:latest

      - name: Build and push syslog signals image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.syslog-signals
          push: true
          tags: ghcr.io/rberbatovci/syslog-signals:latest

      - name: Build and push traps producer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.traps-producer
          push: true
          tags: ghcr.io/rberbatovci/traps-producer:latest

      - name: Build and push traps consumer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.traps-consumer
          push: true
          tags: ghcr.io/rberbatovci/traps-consumer:latest

      - name: Build and push traps signals image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.traps-signals
          push: true
          tags: ghcr.io/rberbatovci/traps-signals:latest

      - name: Build and push netflow producer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.netflow-producer
          push: true
          tags: ghcr.io/rberbatovci/netflow-producer:latest

      - name: Build and push netflow consumer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/Dockerfile.netflow-consumer
          push: true
          tags: ghcr.io/rberbatovci/netflow-consumer:latest